services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./packages/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_APP_NAME=MyReactApp
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/api:/app
      - /app/node_modules
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge