services:
  web:
    container_name: web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_APP_NAME=MyReactApp
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge